import dotenv
import os

dotenv.load_dotenv()

SUCCESS_STATUS_CODE = 200
PARTIAL_CONTENT_STATUS_CODE = 206
UNAUTHORIZED_STATUS_CODE = 401

IS_DEBUG = bool(os.getenv("DEBUG", False))
PROD_SERVER_URL = ""
IS_VIT_AP_SERVER_DOWN = False

CORS_RESOURCE_LIST = {
    r"/api/*": {
        "origins": [
            # if IS_DEBUG else None,
            "http://localhost:5173",
            PROD_SERVER_URL,
            "https://vtop2.vitap.ac.in",
        ]
    },
    r"/": {"origins": "*"},
}

SAMPLE_RESPONSE = {
    "academic_history": {
        "subjects": {
            "Applications of Differential and Difference Equations": "B",
            "Applied Statistics": "B",
            "Arithmetic Problem Solving": "B",
            "Artificial Intelligence": "S",
            "Basic Competitive Coding - I": "B",
            "Basic French": "C",
            "Calculus for Engineers": "C",
            "Chemistry and Environmental Studies": "B",
            "Cloud Computing": "A",
            "Computer Networks": "A",
            "Computer Organization and Architecture": "A",
            "Data Structures and Algorithms": "S",
            "Database Management Systems": "B",
            "Deep Learning": "A",
            "Design Thinking": "A",
            "Digital Logic Design": "A",
            "Discrete Mathematical Structures": "S",
            "Engineering Clinics - II": "S",
            "Engineering Clinics - Raspberry Pi using Python": "A",
            "English for Effective Communication": "E",
            "English for Essential Communication": "B",
            "Entrepreneurship": "A",
            "Ethics and Values": "P",
            "Fundamentals of Aptitude": "S",
            "Fundamentals of Electrical and Electronics Engineering": "B",
            "Getting Started to Skill Enhancement": "C",
            "Introduction to Machine Learning": "B",
            "Modern Physics": "B",
            "Object Oriented Programming": "A",
            "Operating Systems": "A",
            "Problem Solving using Python": "B",
            "Theory of Computation": "B",
        },
        "summary": {
            "A": 10.0,
            "B": 12.0,
            "C": 3.0,
            "CGPA": 8.48,
            "CreditsEarned": 100.0,
            "CreditsRegistered": 100.0,
            "D": 0.0,
            "E": 1.0,
            "F": 0.0,
            "S": 5.0,
        },
    },
    "attendance": {},
    "profile": {
        "appNo": "2021999864",
        "branch": "BTECH",
        "email": "8247092248",
        "name": "VANGIPURAM SRINIVASA SARATH CHANDRA",
        "proctorEmail": "naveen.ranjan@vitap.ac.in",
        "proctorMobileNumber": "Department of Languages",
        "proctorName": "DR.NAVEEN KUMAR RANJAN",
        "profileImageBase64": None,
        "program": "sarath.21bce9853@vitapstudent.ac.in",
        "regNo": "School  Information",
        "school": "Computer Science and Engineering with Specialization in Artificial Intelligence and Machine Learning",
        "token": "MjAyMTk5OTg2NA==",
    },
    "timetable": {
        "Friday": [
            {
                "class": "421-AB-1",
                "code": "STS3006",
                "courseName": "Basic Competitive Coding I",
                "endTime": "09:50",
                "slot": "C1",
                "startTime": "09:00",
            },
            {
                "class": "416-AB-1",
                "code": "STS2006",
                "courseName": "Getting Started to Skill Enhancement",
                "endTime": "10:50",
                "slot": "D1",
                "startTime": "10:00",
            },
            {
                "class": "416-AB-1",
                "code": "CSE4006",
                "courseName": "Deep Learning",
                "endTime": "11:50",
                "slot": "E1",
                "startTime": "11:00",
            },
            {
                "class": "G03-AB-1",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "14:50",
                "slot": "L49",
                "startTime": "14:00",
            },
            {
                "class": "G03-AB-1",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "14:50",
                "slot": "L49",
                "startTime": "14:00",
            },
            {
                "class": "G03-AB-1",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "15:40",
                "slot": "L50",
                "startTime": "14:50",
            },
            {
                "class": "G03-AB-1",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "15:40",
                "slot": "L50",
                "startTime": "14:50",
            },
        ],
        "Monday": [
            {
                "class": "416-AB-1",
                "code": "STS2006",
                "courseName": "Getting Started to Skill Enhancement",
                "endTime": "09:50",
                "slot": "D1",
                "startTime": "09:00",
            },
            {
                "class": "421-AB-1",
                "code": "STS3006",
                "courseName": "Basic Competitive Coding I",
                "endTime": "10:50",
                "slot": "C1",
                "startTime": "10:00",
            },
            {
                "class": "416-AB-1",
                "code": "CSE4006",
                "courseName": "Deep Learning",
                "endTime": "12:50",
                "slot": "TE1",
                "startTime": "12:00",
            },
        ],
        "Saturday": [
            {
                "class": "G13-CB",
                "code": "CSE1008",
                "courseName": "Theory of Computation",
                "endTime": "09:50",
                "slot": "B1",
                "startTime": "09:00",
            },
            {
                "class": "G13-CB",
                "code": "CSE1008",
                "courseName": "Theory of Computation",
                "endTime": "10:50",
                "slot": "B1",
                "startTime": "10:00",
            },
            {
                "class": "115-AB-2",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "11:50",
                "slot": "A1",
                "startTime": "11:00",
            },
            {
                "class": "115-AB-2",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "12:50",
                "slot": "A1",
                "startTime": "12:00",
            },
            {
                "class": "212-AB-2",
                "code": "CSE4001",
                "courseName": "Cloud Computing",
                "endTime": "14:50",
                "slot": "B2",
                "startTime": "14:00",
            },
            {
                "class": "212-AB-2",
                "code": "CSE4001",
                "courseName": "Cloud Computing",
                "endTime": "15:50",
                "slot": "B2",
                "startTime": "15:00",
            },
        ],
        "Sunday": [],
        "Thursday": [
            {
                "class": "416-AB-1",
                "code": "CSE4006",
                "courseName": "Deep Learning",
                "endTime": "10:50",
                "slot": "E1",
                "startTime": "10:00",
            },
            {
                "class": "G13-CB",
                "code": "CSE1008",
                "courseName": "Theory of Computation",
                "endTime": "11:50",
                "slot": "TB1",
                "startTime": "11:00",
            },
            {
                "class": "115-AB-2",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "12:50",
                "slot": "TA1",
                "startTime": "12:00",
            },
            {
                "class": "212-AB-2",
                "code": "CSE4001",
                "courseName": "Cloud Computing",
                "endTime": "16:50",
                "slot": "TB2",
                "startTime": "16:00",
            },
        ],
        "Tuesday": [
            {
                "class": "G13-CB",
                "code": "CSE1008",
                "courseName": "Theory of Computation",
                "endTime": "09:50",
                "slot": "B1",
                "startTime": "09:00",
            },
            {
                "class": "115-AB-2",
                "code": "CSE3003",
                "courseName": "Computer Networks",
                "endTime": "10:50",
                "slot": "A1",
                "startTime": "10:00",
            },
            {
                "class": "421-AB-1",
                "code": "STS3006",
                "courseName": "Basic Competitive Coding I",
                "endTime": "11:50",
                "slot": "C1",
                "startTime": "11:00",
            },
            {
                "class": "416-AB-1",
                "code": "STS2006",
                "courseName": "Getting Started to Skill Enhancement",
                "endTime": "12:50",
                "slot": "TD1",
                "startTime": "12:00",
            },
            {
                "class": "212-AB-2",
                "code": "CSE4001",
                "courseName": "Cloud Computing",
                "endTime": "14:50",
                "slot": "B2",
                "startTime": "14:00",
            },
        ],
        "Wednesday": [
            {
                "class": "416-AB-1",
                "code": "CSE4006",
                "courseName": "Deep Learning",
                "endTime": "09:50",
                "slot": "E1",
                "startTime": "09:00",
            },
            {
                "class": "421-AB-1",
                "code": "STS3006",
                "courseName": "Basic Competitive Coding I",
                "endTime": "11:50",
                "slot": "TC1",
                "startTime": "11:00",
            },
            {
                "class": "416-AB-1",
                "code": "STS2006",
                "courseName": "Getting Started to Skill Enhancement",
                "endTime": "12:50",
                "slot": "D1",
                "startTime": "12:00",
            },
            {
                "class": "G13-CB",
                "code": "CSE1008",
                "courseName": "Theory of Computation",
                "endTime": "15:50",
                "slot": "TBB1",
                "startTime": "15:00",
            },
        ],
    },
}
